modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description="Knock U Back"
logoFile = "icon.png"

[[mixins]]
config="knockuback.mixins.json"

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="[${neo_version_low},)"
ordering="NONE"
side="SERVER"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="SERVER"